# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SessionExchangeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(default=b'', max_length=40, verbose_name=b'session key')),
                ('expires_at', models.DateTimeField(verbose_name=b'expires at')),
            ],
        ),
    ]
